CREATE DATABASE WORK;
USE WORK;
CREATE TABLE EMPLOYE(EMPNO CHAR(4),EMP_NAME VARCHAR(20),DEPT VARCHAR(20),SALARY INT,DOJ DATE NOT NULL,
BRANCH varchar(20) not null,PRIMARY KEY(EMPNO));


INSERT INTO EMPLOYE(EMPNO,EMP_NAME,DEPT,SALARY,DOJ,BRANCH)VALUES('E101','AMIT','PRODUCTION',45000,'12-03-00','BANGLORE');
INSERT INTO EMPLOYE(EMPNO,EMP_NAME,DEPT,SALARY,DOJ,BRANCH)VALUES('E102','AMIT','HR',70000,'03-07-02','BANGLORE');
INSERT INTO EMPLOYE(EMPNO,EMP_NAME,DEPT,SALARY,DOJ,BRANCH)VALUES('E103','SUNITHA','MANAGER',120000,'11-01-01','MYSORE');
INSERT INTO EMPLOYE(EMPNO,EMP_NAME,DEPT,SALARY,DOJ,BRANCH)VALUES('E105','SUNITHA','IT',67000,'01-08-01','MYSORE');
INSERT INTO EMPLOYE(EMPNO,EMP_NAME,DEPT,SALARY,DOJ,BRANCH)VALUES('E106','MAHESH','CIVIL',145000,'20-09-03','MUMBAI');

SELECT * FROM EMPLOYEE;
SELECT EMPNO,SALARY FROM EMPLOYE;
SELECT AVG(SALARY) FROM EMPLOYE;
SELECT COUNT(*) FROM EMPLOYE;
SELECT DISTINCT(EMP_NAME)FROM EMPLOYE;
SELECT SUM(SALARY) FROM EMPLOYE GROUP BY EMP_NAME;
SELECT SALARY FROM EMPLOYE WHERE SALARY>12000;
SELECT EMP_NAME FROM EMPLOYE ORDER BY EMP_NAME ASC;
SELECT EMP_NAME FROM EMPLOYE ORDER BY EMP_NAME desc;
SELECT * FROM EMPLOYE WHERE EMP_NAME='AMIT' AND SALARY>50000;


