CREATE DATABASE departmentss;

USE departmentss;
CREATE TABLE DEPT(DEPTNO INT,DNAME VARCHAR(20),LOC VARCHAR(20));
select * from dept;
ALTER TABLE DEPT ADD COLUMN PINCODE VARCHAR(2) NOT NULL;
ALTER TABLE DEPT DROP COLUMN PINCODE;
ALTER TABLE DEPT CHANGE DNAME DEPT_NAME VARCHAR(20); 
ALTER TABLE DEPT CHANGE COLUMN LOC LOC CHAR(10);
RENAME TABLE DEPT TO DEPARTMENT;
DROP TABLE DEPARTMENT;


